baseURL: https://peacewalker122.github.io/
languageCode: en-us
title: Welcome to my blog
theme: ["archie"]

paginate: 3 # articles per page

params:
  mode: "toggle" # color-mode → light,dark,toggle or auto
  useCDN: false # don't use CDNs for fonts and icons, instead serve them locally.
  mathjax: true # enable MathJax support
  katex: true # enable KaTeX support

# Social Tags
  social:
    - name: "GitHub"
      icon: "github"
      url: "https://github.com/peacewalker122"

    - name: "Linkedin"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/danielanugerah/"

module:
  imports:
  - path: github.com/athul/archie
