baseURL: https://peacewalker122.github.io/
languageCode: en-us
title: peacewalker122
theme: ["PaperMod"]

params:
  homeInfoParams:
    Title: Hi there 👋

  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/peacewalker122"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/danielanugerah"

  showReadingTime: true
  # menu:
  #   main:
  #     - identifier: categories
  #       name: categories
  #       url: /categories/
  #       weight: 10
  #     - identifier: tags
  #       name: tags
  #       url: /tags/
  #       weight: 20
  #     - identifier: example
  #       name: example.org
  #       url: https://example.org
  #       weight: 30

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod
